services:
  - type: web
    name: your-app-name
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn your_module:app
# Exported from Render on 2025-01-17T22:58:02Z
services:
- type: web
  name: oag_store
  runtime: python
  repo: https://github.com/badboigibby/oag_store
  plan: free
  region: oregon
  buildCommand: pip install -r requirements.txt
  startCommand: gunicorn app:app
version: "1"
git commit -m "Add render.yaml"
git push